export const ACCESS_DENIED = 'ACCESS_DENIED'
export const INPUT_EMPTY = 'INPUT_EMPTY'
export const UNAUTHORIZED = 'UNAUTHORIZED'
export const PASSWORD_WRONG_FORMAT = 'PASSWORD_WRONG_FORMAT'
export const START_DATE_NOT_GREATER_THAN_END_DATE = 'START_DATE_NOT_GREATER_THAN_END_DATE'
export const ID_INVALID = 'ID_INVALID'
export const DATE_INVALID = 'DATE_INVALID'
export const STATUS_INVALID = 'STATUS_INVALID'
export const PASSWORD_NOT_STRONG = 'PASSWORD_NOT_STRONG'
export const USER = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXIST: 'EMAIL_USER_EXIST',
  INVALID_USER_EMAIL: 'INVALID_USER_EMAIL',
  USERNAME_OR_PASSWORD_IS_INCORRECT: 'USERNAME_OR_PASSWORD_IS_INCORRECT',
  ACCOUNT_ID_INVALID: 'ACCOUNT_ID_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_IS_BLOCKED: 'ACCOUNT_IS_BLOCKED',
  USER_ATTENDED: 'USER_ATTENDED', // User đã tham dự Event
  USER_NOT_CHECKIN_EVENT: 'USER_NOT_CHECKIN_EVENT',
  USER_HAVE_CHECKED_OUT_EVENT: 'USER_HAVE_CHECKED_OUT_EVENT',
  USER_ID_INVALID: 'USER_ID_INVALID'
}

export const LOGIN = {
  USERNAME_PASSWORD_NOT_CORRECT: 'USERNAME_PASSWORD_NOT_CORRECT',
  ACCOUNT_NOT_VERIFY: 'Your email address has not been verified yet. Please check your inbox for the verification email!',
  SALT_NOT_CORRECT: 'SALT_IS_CORRECT',
  USERNAME_OR_PASSWORD_IS_INCORRECT: 'USERNAME_OR_PASSWORD_IS_INCORRECT',
  EMAIL_INVALID: 'EMAIL_INVALID'
}

export const CATEGORY = {
  SLUG_INVALID: 'SLUG INVALID!',
  KEY_EXISTED: 'KEY_EXISTED',
  CATEGORY_ID_INVALID: 'CATEGORY_ID_INVALID',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_IS_DEFAULT: 'CATEGORY_IS_DEFAULT',
  KEY_INVALID: 'KEY_INVALID',
  TYPE_INVALID: 'TYPE_INVALID'
}

export const UNIT = {
  NAME_EMPTY: 'NAME_EMPTY',
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND'
}

export const REQUEST = {
  START_DATE_INVALID: 'START_DATE_INVALID',
  END_DATE_INVALID: 'END_DATE_INVALID',
  SERVICE_GROUP_EMPTY: 'SERVICE_GROUP_EMPTY'
}

export const EVENT = {
  EVENT_ID_INVALID: 'EVENT_ID_INVALID',
  NAME_INVALID: 'NAME_INVALID',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  YOU_HAVE_NOT_CHECKED_IN_EVENT: 'YOU_HAVE_NOT_CHECKED_IN_EVENT',
  YOU_HAVE_CHECKED_OUT_EVENT: 'YOU_HAVE_CHECKED_OUT_EVENT'
}

export const SESSION = {
  SESSION_ID_INVALID: 'SESSION_ID_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  POINT_INVALID: 'POINT_INVALID',
  NOT_ENOUGH_POINT: 'NOT_ENOUGH_POINT',
  YOU_HAVE_GIVEN_POINT_THIS_SESSION: 'YOU_HAVE_GIVEN_POINT_THIS_SESSION',
  TIME_INVALID: 'TIME_INVALID'
}

export const ARTICLE = {
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  SLUG_INVALID: 'SLUG_INVALID'
}

export const FILES = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_LARGER_THAN_100MB: 'FILE_LARGER_THAN_100MB',
  FORMAT_DOCUMENT_ERROR: 'FORMAT_DOCUMENT_ERROR',
  FORMAT_VIDEO_ERROR: 'FORMAT_VIDEO_ERROR',
  FILE_LARGER_THAN_200MB: 'FILE_LARGER_THAN_200MB'
}

export const CHECK_IN_SESSION = {
  YOU_HAVE_CHECKED_IN: 'YOU_HAVE_CHECKED_IN',
  TIME_UP_CHECK_IN: 'TIME_UP_CHECK_IN',
  ITS_NOT_TIME_YET: 'ITS_NOT_TIME_YET',
  YOU_HAVE_CHECKED_OUT_EVENT: 'YOU_HAVE_CHECKED_OUT_EVENT',
  SESSION_NOT_CHECKED: 'SESSION_NOT_CHECKED'
}

export const NOTIFICATION_USER = {
  TYPE_INVALID: 'TYPE_INVALID',
  TITLE_INVALID: 'TITLE_INVALID',
  LIST_USER_INVALID: 'LIST_USER_INVALID',
  NOTI_NOT_FOUND: 'NOTI_NOT_FOUND'
}

export const SOCKET = {
  SOCKET_IS_NOT_CONNECTED: 'SOCKET_IS_NOT_CONNECTED',
  USER_ID_INVALID: 'USER_ID_INVALID'
}

export const USER_POINT = {
  USER_POINT_NOT_FOUND: 'USER_POINT_NOT_FOUND'
}
export const SCANQR = {
  KEY_SCANQR_NOT_FOUND: 'KEY_SCANQR_NOT_FOUND',
  NOT_CONFIRMED_TO_JOIN_THE_EVENT: 'NOT_CONFIRMED_TO_JOIN_THE_EVENT'
}
export const SURVEY = {
  EMPTY_RESULT: 'RESULT_IS_EMPTY'
}

export const SESSION_SPEAKER = {
  SPEAKER_IS_EXISTED: 'SPEAKER_IS_EXISTED',
  SPEAKER_ID_INVALID: 'SPEAKER_ID_INVALID',
  SPEAKER_NOT_FOUND: 'SPEAKER_NOT_FOUND'
}

export const TYPE_SESSION = {
  EMPTY_RESULT: 'TYPE_SESSION_NOT_FOUND'
}

export const BOOTH = {
  BOOTH_ID_INVALID: 'BOOTH_ID_INVALID',
  BOOTH_NOT_FOUND: 'BOOTH_NOT_FOUND'
}

export const STAFF = {
  INVALID_STAFF_EMAIL: 'INVALID_STAFF_EMAIL',
  STAFF_EXIST: 'EMAIL_STAFF_EXIST',
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  CANT_CREATE_HIGHER_STAFF: 'CANT_CREATE_HIGHER_STAFF',
  CANT_UPDATE_HIGHER_STAFF: 'CANT_UPDATE_HIGHER_STAFF',
  CANT_DELETE_HIGHER_STAFF: 'CANT_DELETE_HIGHER_STAFF'
}

export const ATTENDEE = {
  ATTENDEE_ID_INVALID: 'ATTENDEE_ID_INVALID',
  ATTENDEE_NOT_FOUND: 'ATTENDEE_NOT_FOUND',
  EMAIL_ACB_INVALID: 'EMAIL_ACB_INVALID',
  ATTENDEE_IS_EXISTED: 'ATTENDEE_IS_EXISTED'
}

export const ROLE = {
  NAME_INVALID: 'NAME_INVALID',
  ROLE_ID_INVALID: 'ROLE_ID_INVALID',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_IS_BLOCKED: 'ROLE_IS_BLOCKED'
}

export const POINTGIVING = {
  POINT_NOT_ENOUGH: 'NOT_ENOUGH_POINT',
  EXPIRED_DAY: 'EXPIRED_DAY',
  POINT_INVALID: 'POINT_INPUT_INVALID'
}

export const SETTING = {
  KEY_INVALID: 'KEY_INVALID',
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND'
}

export const SYSTEM = {
  SYSTEM_IS_REUQUIRED: 'SYSTEM_IS_REUQUIRED'
}
export const UUID = {
  DATA_NOT_UUID_VALUE: 'DATA_NOT_UUID_VALUE'
}
